### ISSUE TITLE
Thesis Structure

### ISSUE THREAD

**Issue by KikeM** [KikeM/msc-literature-review#26]
- [ ] Literature Review: Research questions and related works.
- [ ] FOM, ROM and HROM definition and presentation.
- [ ] Problem presentation:
    - [ ] One-Dimensional Burger's Equation
    - [ ] Oscillating cylinder - 2D Navier-Stokes equations. 
- [ ] Appendices:
    - [ ] Manufactured Problems: Steady-State and Transient.
    - [ ] Geometrical Conservation Laws: Constant solution.
