### ISSUE TITLE
ROM : POD-Galerkin for the linear heat equation in 1D

### ISSUE THREAD

**Issue by KikeM** [KikeM/msc-literature-review#8]
- [x] Generic FOM definition.
- [x] Method of Manufactured Solutions.
- [x] Generic ROM definition: Reduced Basis Method, from local to global support.
- [x] Basis construction (POD). 
- [x] Lifting function (#3, #7)
- [x] ROM integration.
- [x] FOM reconstruction.
